CC=g++ 
STRIP=strip
OBJ=test_display_init_scheme
OBJS=test_display_init_scheme.cpp 
CFLAGS= -Wall -g -lm 
$(OBJ):$(OBJS)
	$(CC) $(CFLAGS) $^ -o $@
	$(STRIP) $@
$*.o:$%.c
	$(CC) $(CFLAGS) -c $< -o $@ 
.PHONY:clean
clean:
	$(RM) *.o test_display_init_scheme
